spring.application.name=cryptopal-core

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cryptopal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cryptopal}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cryptopal}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.jpa.open-in-view=false